### PR TITLE
Fix build on Node >= 12

### PR DESCRIPTION
**Pull request by Minishlink**
Temporary solution for #91 until Gulp is upgraded to v4

### CODE REVIEW

**Comment by steren** [comment]
This seems like a workaround. Have you evaluated the effort of fixing #91 properly? Does it require moving to a new version of gulp, and a lot of re-write?

**Comment by Minishlink** [comment]
Yes this is workaround. A proper fix would indeed require a gulp upgrade to v4 : upgrade the version, changing the gulpfile to a new format and probably also upgrade some plugins. I haven't used gulp for many years so someone might be better fitted to do this upgrade.

**Comment by xlfe** [comment]
For info, I was able to upgrade gulp  and node with a few minor changes https://github.com/psithur-com/stackdriver-errors-js/commit/a0ff987aaa31c039dd78e49a79025dbd4b18b81a

**Comment by steren** [comment]
@xlfe would you mind opening a Pull Request with this upgrade to gulp 4?

**Pull request closed without merging**
