### PR TITLE
Added nvmrc for Node v9 to project

### PR DESCRIPTION
**Pull request by richardson-trevor**
If you'd prefer to pin this down even further just let me know. Thought this would be a good place to start to give people awareness for testing purposes, etc.

### CODE REVIEW

**Comment by steren** [comment]
thanks a lot, sorry, Travis is still unhappy: `Assertion `args[1]->IsString()' failed.`

I should be able to take a look at this within a week if needed.

**Comment by steren** [comment]
To be clearer: Travis failing is not due to your PR, but I want to make sure it is green before merging PRs.

**Comment by richardson-trevor** [comment]
Absolutely. If you'd be okay with https://github.com/gulpjs/gulp/issues/2162#issuecomment-385197164, I think we could move safely to v10. The other options mentioned [here](https://github.com/gulpjs/gulp/issues/2162) seemed a little sketchy.

**Comment by richardson-trevor** [comment]
Scratch that. It looks like the resolutions block is specific to yarn. Looks like our only option would be to instead pull in the later version of `natives` as a dev dependency or similar. 😏

**Comment by richardson-trevor** [comment]
I updated to use Node v9 since that's what master is using now with the issues that came up recently with the builds.

**Pull request merged**
